sdlc maintainance

diff --git a/.sdlc/build-dist b/.sdlc/build-dist
--- a/.sdlc/build-dist
+++ b/.sdlc/build-dist
@@ -15,13 +15,18 @@ buildtime=$(TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ')
 git_hash="$(git rev-parse HEAD)"
 git_dirty="$(test -n "`git status --porcelain`" && echo "+CHANGES" || true)"
 git_commit="${git_hash}${git_dirty}"
-echo "building ${GH_REPO}"
+echo "building ${REPO_NAME}"
 echo "version : ${APP_VERSION}"
 echo "git : ${git_commit}"
 echo "build time : ${buildtime}"
 
 [[ -z "$DIST_DIR" ]] && {
   echo "no dist dir set"
+  exit 1
+}
+
+hash zip 2>/dev/null || {
+  echo "missing zip executable"
   exit 1
 }
 
@@ -39,18 +44,18 @@ for dir in $(find "$CMDS_DIR" -mindepth 1 -maxdepth 1 -type d); do
     target_goos=$(echo $platform | cut -d/ -f1)
     target_goarch=$(echo $platform | cut -d/ -f2)
     echo "building for ${target_goos} ${target_goarch}"
-    platform_dist_basename="${GH_REPO}-${APP_VERSION}_${target_goos}_${target_goarch}"
+    platform_dist_basename="${REPO_NAME}-${APP_VERSION}_${target_goos}_${target_goarch}"
     platform_dist_dir="${DIST_DIR}/${platform_dist_basename}"
     mkdir -p "$platform_dist_dir"
     ext=''
     [[ "windows" = "$target_goos" ]] && ext='.exe'
     built="${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}"
     GOOS="$target_goos" GOARCH="$target_goarch" go build -mod vendor -ldflags "-s \
-    -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.Version=${APP_VERSION} \
-    -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.BuildTime=${buildtime} \
-    -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.GitCommit=${git_commit}" \
+    -X ${REPO_HOST}/${REPO_OWNER}/${REPO_NAME}/lib/core.Version=${APP_VERSION} \
+    -X ${REPO_HOST}/${REPO_OWNER}/${REPO_NAME}/lib/core.BuildTime=${buildtime} \
+    -X ${REPO_HOST}/${REPO_OWNER}/${REPO_NAME}/lib/core.GitCommit=${git_commit}" \
     -o "$built" \
-    "github.com/${GH_OWNER}/${GH_REPO}/cmd/${app_name}"
+    "${REPO_HOST}/${REPO_OWNER}/${REPO_NAME}/cmd/${app_name}"
     [[ -e "$built" ]] || {
       echo "expected file not found: ${built}"
       exit 1
