ci.yml release.yml gh-release

diff --git a/.sdlc/gh-release b/.sdlc/gh-release
--- a/.sdlc/gh-release
+++ b/.sdlc/gh-release
@@ -9,11 +9,11 @@ PRJ_HOME="$( cd -P "$( dirname "$SDLC_DIR" )" && pwd )"
 
 source "${SDLC_DIR}/config"
 
-git_dirty=$(git status --porcelain)
-[[ -n "$git_dirty" ]] && {
-  echo 'uncommitted changes detected: aborting release'
-  exit 1
-}
+# git_dirty=$(git status --porcelain)
+# [[ -n "$git_dirty" ]] && {
+#   echo 'uncommitted changes detected: aborting release'
+#   exit 1
+# }
 
 [[ -z "$GH_TOKEN" ]] && {
   echo "Missing GH_TOKEN"
@@ -21,10 +21,10 @@ git_dirty=$(git status --porcelain)
 }
 
 # https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
-command -v ghr >/dev/null || {
-  echo "ghr not found"
-  exit 1
-}
+# command -v ghr >/dev/null || {
+#   echo "ghr not found"
+#   exit 1
+# }
 
 [[ -z "$REPO_OWNER" ]] && {
   echo "no gh owner"
@@ -40,26 +40,30 @@ if [ -z "$APP_VERSION" ]; then
   exit 1
 fi
 
-RELEASE_VERSION="v$APP_VERSION"
-git tag -a "${RELEASE_VERSION}" -m "release version ${RELEASE_VERSION}"
-git push origin "${RELEASE_VERSION}"
+cat "${SDLC_DIR}/config"
 
-if [ "$1" = "--prod" ]; then
-  PRERELEASE=''
-else
-  PRERELEASE='--prerelease'
-fi
+exit 0
 
-echo "Release $PRJ_HOME version $RELEASE_VERSION $PRERELEASE"
-
-"${SDLC_DIR}/build-dist"
-
-[[ -z "$DIST_DIR" ]] && {
-  echo "dist directory not found: ${DIST_DIR}"
-  exit 1
-}
-
-#ghr -t "$GH_TOKEN" -u "$REPO_OWNER" -r "$REPO_NAME" "$PRERELEASE" "$RELEASE_VERSION" "$DIST_DIR"
-GHR_COMMAND="ghr -t ${GH_TOKEN} -u ${REPO_OWNER} -r ${REPO_NAME} ${PRERELEASE} ${RELEASE_VERSION} ${DIST_DIR}"
-echo "$GHR_COMMAND"
-sh -c "$GHR_COMMAND"
+# RELEASE_VERSION="v$APP_VERSION"
+# git tag -a "${RELEASE_VERSION}" -m "release version ${RELEASE_VERSION}"
+# git push origin "${RELEASE_VERSION}"
+#
+# if [ "$1" = "--prod" ]; then
+#   PRERELEASE=''
+# else
+#   PRERELEASE='--prerelease'
+# fi
+#
+# echo "Release $PRJ_HOME version $RELEASE_VERSION $PRERELEASE"
+#
+# "${SDLC_DIR}/build-dist"
+#
+# [[ -z "$DIST_DIR" ]] && {
+#   echo "dist directory not found: ${DIST_DIR}"
+#   exit 1
+# }
+#
+# #ghr -t "$GH_TOKEN" -u "$REPO_OWNER" -r "$REPO_NAME" "$PRERELEASE" "$RELEASE_VERSION" "$DIST_DIR"
+# GHR_COMMAND="ghr -t ${GH_TOKEN} -u ${REPO_OWNER} -r ${REPO_NAME} ${PRERELEASE} ${RELEASE_VERSION} ${DIST_DIR}"
+# echo "$GHR_COMMAND"
+# sh -c "$GHR_COMMAND"
