updates

diff --git a/.sdlc/update b/.sdlc/update
--- a/.sdlc/update
+++ b/.sdlc/update
@@ -4,14 +4,14 @@ set -e
 
 TOOL_SOURCE="${BASH_SOURCE[0]}"
 while [ -h "$TOOL_SOURCE" ] ; do TOOL_SOURCE="$(readlink "$TOOL_SOURCE")"; done
-HACK_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
-PRJ_HOME="$( cd -P "$( dirname "$HACK_DIR" )" && pwd )"
+SDLC_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
+PRJ_HOME="$( cd -P "$( dirname "$SDLC_DIR" )" && pwd )"
 
 cd "$PRJ_HOME"
 
 command -v dep >/dev/null || {
-    echo "dep not found"
-    exit 1
+  echo "dep not found"
+  exit 1
 }
 
-dep ensure -update
+dep ensure -update -v
