scripts

diff --git a/scripts/build-dist b/scripts/build-dist
--- a/scripts/build-dist
+++ b/scripts/build-dist
@@ -31,32 +31,32 @@ mkdir -p "$DIST_DIR"
 platforms="windows/amd64 linux/amd64 darwin/amd64"
 
 for dir in $(find "$CMDS_DIR" -mindepth 1 -maxdepth 1 -type d); do
-	app_name=$(basename "$dir")
+  app_name=$(basename "$dir")
     echo " =====     Process ${app_name} ${dir}     ====="
     for platform in $platforms; do
-        cd "$PRJ_HOME"
-        target_goos=$(echo $platform | cut -d/ -f1)
-        target_goarch=$(echo $platform | cut -d/ -f2)
-        echo "building for ${target_goos} ${target_goarch}"
-        platform_dist_basename="${GH_REPO}-${APP_VERSION}_${target_goos}_${target_goarch}"
-        platform_dist_dir="${DIST_DIR}/${platform_dist_basename}"
-        mkdir -p "$platform_dist_dir"
-        ext=''
-        [[ "windows" = "$target_goos" ]] && ext='.exe'
-        built="${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}"
-        GOOS="$target_goos" GOARCH="$target_goarch" go build -ldflags "-s \
-      -X main.Version=${APP_VERSION} \
-      -X main.BuildTime=${buildtime} \
-      -X main.GitCommit=${git_commit}" \
+      cd "$PRJ_HOME"
+      target_goos=$(echo $platform | cut -d/ -f1)
+      target_goarch=$(echo $platform | cut -d/ -f2)
+      echo "building for ${target_goos} ${target_goarch}"
+      platform_dist_basename="${GH_REPO}-${APP_VERSION}_${target_goos}_${target_goarch}"
+      platform_dist_dir="${DIST_DIR}/${platform_dist_basename}"
+      mkdir -p "$platform_dist_dir"
+      ext=''
+      [[ "windows" = "$target_goos" ]] && ext='.exe'
+      built="${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}"
+      GOOS="$target_goos" GOARCH="$target_goarch" go build -ldflags "-s \
+      -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.Version=${APP_VERSION} \
+      -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.BuildTime=${buildtime} \
+      -X github.com/${GH_OWNER}/${GH_REPO}/lib/core.GitCommit=${git_commit}" \
       -o "$built" \
       "github.com/${GH_OWNER}/${GH_REPO}/cmd/${app_name}"
-        [[ -e "$built" ]] || {
-            echo "expected file not found: ${built}"
-            exit 1
-        }
-        mv "${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}" "${platform_dist_dir}/${app_name}${ext}"
-        # cd "$DIST_DIR"
-        # zip -r "${platform_dist_basename}.zip" "$platform_dist_basename"
-        # rm -r "$platform_dist_basename"
+      [[ -e "$built" ]] || {
+        echo "expected file not found: ${built}"
+        exit 1
+      }
+      mv "${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}" "${platform_dist_dir}/${app_name}${ext}"
+      # cd "$DIST_DIR"
+      # zip -r "${platform_dist_basename}.zip" "$platform_dist_basename"
+      # rm -r "$platform_dist_basename"
     done
 done
diff --git a/scripts/gh-release b/scripts/gh-release
--- a/scripts/gh-release
+++ b/scripts/gh-release
@@ -11,33 +11,33 @@ source "${HACK_DIR}/config"
 
 git_dirty=$(git status --porcelain)
 [[ -n "$git_dirty" ]] && {
-    echo 'uncommitted changes detected: aborting release'
-    exit 1
+  echo 'uncommitted changes detected: aborting release'
+  exit 1
 }
 
 [[ -z "$GH_TOKEN" ]] && {
-    echo "Missing GH_TOKEN"
-    exit 1
+  echo "Missing GH_TOKEN"
+  exit 1
 }
 
 # https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
 command -v ghr >/dev/null || {
-    echo "ghr not found"
-    exit 1
+  echo "ghr not found"
+  exit 1
 }
 
 [[ -z "$GH_OWNER" ]] && {
-    echo "no gh owner"
-    exit 1
+  echo "no gh owner"
+  exit 1
 }
 [[ -z "$GH_REPO" ]] && {
-    echo "no gh repo"
-    exit 1
+  echo "no gh repo"
+  exit 1
 }
 
 if [ -z "$APP_VERSION" ]; then
-    echo 'no release version supplied. $APP_VERSION expected'
-    exit 1
+  echo 'no release version supplied. $APP_VERSION expected'
+  exit 1
 fi
 
 RELEASE_VERSION="v$APP_VERSION"
@@ -45,9 +45,9 @@ git tag -a "${RELEASE_VERSION}" -m "release version ${RELEASE_VERSION}"
 git push origin "${RELEASE_VERSION}"
 
 if [ "$1" = "--prod" ]; then
-    PRERELEASE=''
+  PRERELEASE=''
 else
-    PRERELEASE='--prerelease'
+  PRERELEASE='--prerelease'
 fi
 
 echo "Release $PRJ_HOME version $RELEASE_VERSION $PRERELEASE"
@@ -55,8 +55,8 @@ echo "Release $PRJ_HOME version $RELEASE_VERSION $PRERELEASE"
 "${HACK_DIR}/build-dist"
 
 [[ -z "$DIST_DIR" ]] && {
-    echo "dist directory not found: ${DIST_DIR}"
-    exit 1
+  echo "dist directory not found: ${DIST_DIR}"
+  exit 1
 }
 
 #ghr -t "$GH_TOKEN" -u "$GH_OWNER" -r "$GH_REPO" "$PRERELEASE" "$RELEASE_VERSION" "$DIST_DIR"
