introduce dep

diff --git a/scripts/build-dist b/scripts/build-dist
--- a/scripts/build-dist
+++ b/scripts/build-dist
@@ -8,12 +8,13 @@ SCRIPTS_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
 PRJ_HOME="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"
 
 source "${SCRIPTS_DIR}/config"
+CMDS_DIR="${PRJ_HOME}/cmd"
 
 buildtime=$(TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ')
 git_hash="$(git rev-parse HEAD)"
 git_dirty="$(test -n "`git status --porcelain`" && echo "+CHANGES" || true)"
 git_commit="${git_hash}${git_dirty}"
-echo "building gip"
+echo "building ${GH_REPO}"
 echo "version : ${GIP_VERSION}"
 echo "git : ${git_commit}"
 echo "build time : ${buildtime}"
@@ -24,30 +25,38 @@ echo "build time : ${buildtime}"
 }
 
 [[ -d "${PRJ_HOME}/bin" ]] && rm -r "${PRJ_HOME}/bin"
-[[ -d "${PRJ_HOME}/pkg" ]] && rm -r "${PRJ_HOME}/pkg"
 [[ -d "$DIST_DIR" ]] && rm -r "$DIST_DIR"
 mkdir -p "$DIST_DIR"
 
-hash gb 2>/dev/null || {
-    go get -u github.com/constabulary/gb/...
-}
-
 platforms="windows/amd64 linux/amd64 darwin/amd64"
 
-for platform in $platforms; do
-	target_goos=$(echo $platform | cut -d/ -f1)
-	target_goarch=$(echo $platform | cut -d/ -f2)
-    echo "building for ${target_goos} ${target_goarch}"
-    GOOS="$target_goos" GOARCH="$target_goarch" gb build -ldflags "-s \
-  -X main.version=${GIP_VERSION} \
-  -X main.buildTime=${buildtime} \
-  -X main.gitCommit=${git_commit}" all > /dev/null
-    ext=''
-    [[ "windows" = "$target_goos" ]] && ext='.exe'
-    built="${PRJ_HOME}/bin/gip-${target_goos}-${target_goarch}${ext}"
-    [[ -e "$built" ]] || {
-        echo "expected file not found: ${built}"
-        exit 1
-    }
-    mv "${PRJ_HOME}/bin/gip-${target_goos}-${target_goarch}${ext}" "$DIST_DIR"
+for dir in $(find "$CMDS_DIR" -mindepth 1 -maxdepth 1 -type d); do
+	app_name=$(basename "$dir")
+    echo " =====     Process ${app_name} ${dir}     ====="
+    for platform in $platforms; do
+        cd "$PRJ_HOME"
+        target_goos=$(echo $platform | cut -d/ -f1)
+        target_goarch=$(echo $platform | cut -d/ -f2)
+        echo "building for ${target_goos} ${target_goarch}"
+        platform_dist_basename="${GH_REPO}-${APP_VERSION}_${target_goos}_${target_goarch}"
+        platform_dist_dir="${DIST_DIR}/${platform_dist_basename}"
+        mkdir -p "$platform_dist_dir"
+        ext=''
+        [[ "windows" = "$target_goos" ]] && ext='.exe'
+        built="${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}"
+        GOOS="$target_goos" GOARCH="$target_goarch" go build -ldflags "-s \
+      -X main.version=${APP_VERSION} \
+      -X main.buildTime=${buildtime} \
+      -X main.gitCommit=${git_commit}" \
+      -o "$built" \
+      "github.com/${GH_OWNER}/${GH_REPO}/cmd/${app_name}"
+        [[ -e "$built" ]] || {
+            echo "expected file not found: ${built}"
+            exit 1
+        }
+        mv "${PRJ_HOME}/bin/${app_name}-${target_goos}-${target_goarch}${ext}" "${platform_dist_dir}/${app_name}${ext}"
+        # cd "$DIST_DIR"
+        # zip -r "${platform_dist_basename}.zip" "$platform_dist_basename"
+        # rm -r "$platform_dist_basename"
+    done
 done
